services:
  backend:
    container_name: infopiste-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGO_DB_URL: mongodb://user:password@mongo:27017/infopiste?authSource=admin
      REDIS_HOST: redis
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      TENANT_ID: ${TENANT_ID}
    depends_on:
      - mongo
      - redis
  frontend:
    container_name: infopiste-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - backend

  mongo:
    container_name: infopiste-mongo
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    container_name: infopiste-redis
    image: redis:8

volumes:
  mongo_data:
