services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "1234"
    environment:
      MONGO_DB_URL: mongodb://user:password@mongo:27017
      REDIS_HOST: redis
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      TENANT_ID: ${TENANT_ID}
      LOAD_MOCK_DATA: ${LOAD_MOCK_DATA}
      GROUP_ID: ${GROUP_ID}
      FILE_ID: ${FILE_ID}
      SHEET_NAME: ${SHEET_NAME}
      FOLDER_ID: ${FOLDER_ID}  
    depends_on:
      - mongo
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:8080"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 1234
      NGINX_PORT: 8080
    depends_on:
      - backend
  mongo:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    image: redis:8

volumes:
  mongo_data:
