services:
  backend:
    image: ohtuinfopiste/infopiste-backend:staging
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"

  frontend:
    image: ohtuinfopiste/infopiste-frontend:staging
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - backend
