services:
  backend:
    image: ohtuinfopiste/infopiste-backend:staging
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    env_file:
      - ./backend/.env
  frontend:
    image: ohtuinfopiste/infopiste-frontend:staging
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env

volumes:
  mongo_data:
