services:
  backend:
    image: infopiste-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"

  frontend:
    image: infopiste-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - backend
