services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGO_DB_URL: mongodb://test_user:test_password@mongo:27017
      PORT: 1234
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    depends_on:
      - mongo
      - backend

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: test_password

volumes:
  mongo_data:
