apiVersion: apps/v1
kind: Deployment
metadata:
  name: infopiste-frontend-deployment
  namespace: ohtuprojekti-staging
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"infopiste-frontend:staging","namespace":"ohtuprojekti-staging"},"fieldPath":"spec.template.spec.containers[?(@.name==\"frontend\")].image","pause":"false"}]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infopiste-frontend
  template:
    metadata:
      labels:
        app: infopiste-frontend
    spec:
      containers:
        - name: frontend
          image: infopiste-frontend:staging
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "50Mi"
              cpu: "50m"

---

apiVersion: v1
kind: Service
metadata:
  name: infopiste-frontend-service
  namespace: ohtuprojekti-staging
spec:
  selector:
    app: infopiste-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
