apiVersion: apps/v1
kind: Deployment
metadata:
  name: infopiste-frontend
  namespace: ohtuprojekti-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infopiste-frontend
  template:
    metadata:
      labels:
        app: infopiste-frontend
    spec:
      containers:
        - name: frontend
          image: image-registry.openshift-image-registry.svc:5000/ohtuprojekti-staging/infopiste-frontend:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
      volumes:
        - name: nginx-cache
          emptyDir: {}
