apiVersion: apps/v1
kind: Deployment
metadata:
  name: infopiste-mongo-deployment
  namespace: ohtuprojekti-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infopiste-mongo
  template:
    metadata:
      labels:
        app: infopiste-mongo
    spec:
      containers:
        - name: my-mongo
          image: mongo:8
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: infopiste-config
                  key: MONGO_INITDB_ROOT_USERNAME 
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: infopiste-config
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: infopiste-mongo-volume
      volumes:
        - name: infopiste-mongo-volume
          persistentVolumeClaim:
            claimName: infopiste-mongo-claim

---

apiVersion: v1
kind: Service
metadata:
  name: infopiste-mongo-service
spec:
  selector:
    app: infopiste-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
