apiVersion: apps/v1
kind: Deployment
metadata:
  name: infopiste-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infopiste-mongo
  template:
    metadata:
      labels:
        app: infopiste-mongo
    spec:
      containers:
        - name: infopiste-mongo
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: infopiste-config
                  key: MONGO_INITDB_ROOT_USERNAME 
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: infopiste-config
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: infopiste-mongo-volume
      volumes:
        - name: infopiste-mongo-volume
          persistentVolumeClaim:
            claimName: infopiste-mongo-claim
