apiVersion: apps/v1
kind: Deployment
metadata:
  name: infopiste-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infopiste-redis
  template:
    metadata:
      labels:
        app: infopiste-redis
    spec:
      containers:
        - name: infopiste-redis
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: infopiste-config
                  key: REDIS_PASSWORD
          command: ["redis-server"]
          args: ["--requirepass", "${REDIS_PASSWORD}"]
