kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: infopiste-claim
  namespace: ohtuprojekti-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: data-2
  volumeMode: Filesystem
