name: End to end tests

on:
  push:
    branches: [main, optimize-ci-e2e]
    paths:
      - 'frontend/**'
      - '.github/workflows/end-to-end.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/end-to-end.yaml'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 22

        - name: get installed playwright version
          id: playwright-version
          run: echo "PLAYWRIGHT VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV

        - name: cache playwright binaries
          uses: actions/cache@v3
          id: playwright-cache
          with:
            path: |
              ~/.cache/ms-playwright
            key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }} 
            restore-keys: |
              ${{ runner.os }}-playwright-

        - name: install Playwright browsers
          if: steps.playwright-cache.outputs.cache-hit != 'true'
          run: npx playwright install --with-deps

        - name: e2e tests
          run: npm run e2e
