name: Frontend tests

on:
  push:
    branches: [main, e2e-tests]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: frontend unit tests
        run: npm run test

      - name: get installed playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test --json | jq -r '.dependencies["@playwright/test"].version')
          echo "Detected Playwright version: $PLAYWRIGHT_VERSION"
          echo "::set-output name=version::$PLAYWRIGHT_VERSION"

      # cache playwright's browser binaries for faster CI
      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: install Playwright system dependencies
        run: npx playwright install-deps
      - name: install browsers for end to end tests
        run: npx playwright install
      - name: end to end tests
        run: npx playwright test --workers=4
